-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 17:55:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy_db` DEFAULT CHARACTER SET utf8 ;
USE `paymybuddy_db` ;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`user` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`bankAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`bankAccount` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`bankAccount` (
  `bankAccount_ID` INT NOT NULL AUTO_INCREMENT,
  `bankAccountNumber` VARCHAR(27) NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`bankAccount_ID`),
  INDEX `fk_bankAccount_user_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_bankAccount_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `paymybuddy_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`balance` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`balance` (
  `balance_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`balance_id`, `user_user_id`),
  INDEX `fk_balance_user1_idx` (`user_user_id` ASC) VISIBLE,
  UNIQUE INDEX `balance_id_UNIQUE` (`balance_id` ASC) VISIBLE,
  CONSTRAINT `fk_balance_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `paymybuddy_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`transaction` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `datetime` TIMESTAMP NULL,
  `transaction_amount` DOUBLE NULL,
  `balance_balance_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `datetime_UNIQUE` (`datetime` ASC) VISIBLE,
  INDEX `fk_transaction_balance1_idx` (`balance_balance_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_balance1`
    FOREIGN KEY (`balance_balance_id`)
    REFERENCES `paymybuddy_db`.`balance` (`balance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transactionDescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`transactionDescription` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transactionDescription` (
  `description` VARCHAR(255) NULL,
  `transaction_transaction_id` INT NOT NULL,
  PRIMARY KEY (`transaction_transaction_id`),
  CONSTRAINT `fk_transactionDescription_transaction1`
    FOREIGN KEY (`transaction_transaction_id`)
    REFERENCES `paymybuddy_db`.`transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transactionRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`transactionRecords` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transactionRecords` (
  `transaction_records` VARCHAR(255) NULL,
  `transaction_transaction_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  `transactionDescription_transaction_transaction_id` INT NOT NULL,
  PRIMARY KEY (`transaction_transaction_id`, `user_user_id`, `transactionDescription_transaction_transaction_id`),
  INDEX `fk_transactionRecords_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_transactionRecords_transactionDescription1_idx` (`transactionDescription_transaction_transaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactionRecords_transaction1`
    FOREIGN KEY (`transaction_transaction_id`)
    REFERENCES `paymybuddy_db`.`transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactionRecords_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `paymybuddy_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactionRecords_transactionDescription1`
    FOREIGN KEY (`transactionDescription_transaction_transaction_id`)
    REFERENCES `paymybuddy_db`.`transactionDescription` (`transaction_transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transactionStatut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`transactionStatut` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transactionStatut` (
  `statut` TINYINT NULL,
  `transaction_transaction_id` INT NOT NULL,
  PRIMARY KEY (`transaction_transaction_id`),
  CONSTRAINT `fk_transactionStatut_transaction1`
    FOREIGN KEY (`transaction_transaction_id`)
    REFERENCES `paymybuddy_db`.`transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`errors` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`errors` (
  `errors_id` INT NOT NULL AUTO_INCREMENT,
  `errormessage` VARCHAR(100) NULL,
  `transaction_transaction_id` INT NOT NULL,
  PRIMARY KEY (`errors_id`),
  INDEX `fk_errors_transaction1_idx` (`transaction_transaction_id` ASC) VISIBLE,
  UNIQUE INDEX `errors_id_UNIQUE` (`errors_id` ASC) VISIBLE,
  CONSTRAINT `fk_errors_transaction1`
    FOREIGN KEY (`transaction_transaction_id`)
    REFERENCES `paymybuddy_db`.`transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
