-- MySQL Script generated by MySQL Workbench
-- Fri Feb 11 14:31:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paymybuddy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `paymybuddy_db` ;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`role` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`user` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`user` (
  `id` INT NOT NULL,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `enable` BIT(1) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKn82ha3ccdebhokx3a8fgdqeyy` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKn82ha3ccdebhokx3a8fgdqeyy`
    FOREIGN KEY (`role_id`)
    REFERENCES `paymybuddy_db`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`balance` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`balance` (
  `user_id` INT NOT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK5alq49p112j6qwiho4xhq75fx`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy_db`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`bank_account` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`bank_account` (
  `id` INT NOT NULL,
  `bank_account_number` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK92iik4jwhk7q385jubl2bc2mm` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK92iik4jwhk7q385jubl2bc2mm`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy_db`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`transfer` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`transfer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transfer_amount` FLOAT NULL DEFAULT NULL,
  `date_time` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `connection_balance_id` INT NULL DEFAULT NULL,
  `user_balance_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK3dipewm4i8ckt1yuiph50q36m` (`connection_balance_id` ASC) VISIBLE,
  INDEX `FKd7jvpaa351ielabnf99j69520` (`user_balance_id` ASC) VISIBLE,
  CONSTRAINT `FK3dipewm4i8ckt1yuiph50q36m`
    FOREIGN KEY (`connection_balance_id`)
    REFERENCES `paymybuddy_db`.`balance` (`user_id`),
  CONSTRAINT `FKd7jvpaa351ielabnf99j69520`
    FOREIGN KEY (`user_balance_id`)
    REFERENCES `paymybuddy_db`.`balance` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`payment` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`payment` (
  `id` INT NOT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `date_time` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `payment_direction` VARCHAR(255) NULL DEFAULT NULL,
  `bank_account_id` INT NULL DEFAULT NULL,
  `user_balance_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKe12wsjq2ebylksh1vppycoa6h` (`bank_account_id` ASC) VISIBLE,
  INDEX `FKqb31shnl86yerveao5cm1yoqa` (`user_balance_id` ASC) VISIBLE,
  INDEX `FK4spfnm9si9dowsatcqs5or42i` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK4spfnm9si9dowsatcqs5or42i`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy_db`.`user` (`id`),
  CONSTRAINT `FKe12wsjq2ebylksh1vppycoa6h`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `paymybuddy_db`.`bank_account` (`id`),
  CONSTRAINT `FKqb31shnl86yerveao5cm1yoqa`
    FOREIGN KEY (`user_balance_id`)
    REFERENCES `paymybuddy_db`.`balance` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`company_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`company_account` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`company_account` (
  `id` INT NOT NULL,
  `bank_account_number` VARCHAR(255) NULL DEFAULT NULL,
  `sold` FLOAT NULL DEFAULT NULL,
  `payment_id` INT NULL DEFAULT NULL,
  `transfer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqwkrh54e5r3oitnaq5tai8lhq` (`payment_id` ASC) VISIBLE,
  INDEX `FK2nxkqlilupt1iig81wq8r4nc8` (`transfer_id` ASC) VISIBLE,
  CONSTRAINT `FK2nxkqlilupt1iig81wq8r4nc8`
    FOREIGN KEY (`transfer_id`)
    REFERENCES `paymybuddy_db`.`transfer` (`id`),
  CONSTRAINT `FKqwkrh54e5r3oitnaq5tai8lhq`
    FOREIGN KEY (`payment_id`)
    REFERENCES `paymybuddy_db`.`payment` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paymybuddy_db`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy_db`.`connections` ;

CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`connections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` DATETIME(6) NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `connection_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKll23ohqygyfb7ev1ob06m1c0k` (`connection_id` ASC) VISIBLE,
  INDEX `FKatesnk9iuu3hcyyo85p75blww` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKatesnk9iuu3hcyyo85p75blww`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy_db`.`user` (`id`),
  CONSTRAINT `FKll23ohqygyfb7ev1ob06m1c0k`
    FOREIGN KEY (`connection_id`)
    REFERENCES `paymybuddy_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `paymybuddy_db`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy_db`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

